matrix:
  include:
    - language: node_js
      node_js:
      - 10
      cache: npm
      install:
      - npm install codecov -g
      - npm install --prefix=src/app/static
      - npm run build --prefix=src/app/static
      script: npm test --prefix=src/app/static
      after_success:
      - codecov -f src/app/static/coverage/*.json
    - language: java
      before_cache:
      - rm -f  $HOME/src/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/src/.gradle/caches/*/plugin-resolution/
      cache:
          directories:
          - $HOME/src/app/.gradle/caches/
          - $HOME/src/app/.gradle/wrapper/
          - $HOME/src/app/static/node_modules
      jdk:
      - openjdk8
      install:
      - npm install codecov -g
      - npm install --prefix=src/app/static
      - ./src/gradlew -p src
      before_script:
      - sudo /etc/init.d/postgresql stop
      - ./scripts/run-dependencies.sh
      script:
      - ./src/gradlew -p src app::test
      - ./src/gradlew -p src userCLI::test
      after_script:
      - ./src/gradlew -p src app::jacocoTestReport
      - codecov -f src/app/coverage/test/*.xml
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - ./src/userCLI/scripts/build
      - ./src/userCLI/scripts/push
      - ./scripts/travis.sh
      services:
      - docker
