steps:
  - label: ":construction_worker::mag: Make shared build env"
    command: buildkite/make-build-env.sh

  - wait

  - label: ":mag: Build app and CLI images"
    command: buildkite/build.sh

  - label: ":mag: Test back-end"
    command: buildkite/test.sh

  - label: ":mag: Test front-end"
    command: buildkite/test-front-end.sh

  - wait

  - label: ":shipit: Push images"
    command: buildkite/push.sh
