name: Make Shared Environment

env:
  NODE_VERSION: 20

inputs:
  install-packages:
    description: 'Whether or not to install npm packages'
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup Environment (PR)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "CI_ORG=mrcide" >> ${GITHUB_ENV}
        echo "CI_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
        echo "CI_BRANCH=${{ github.head_ref }}" >> ${GITHUB_ENV}

    - name: Setup Environment (Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "CI_ORG=mrcide" >> ${GITHUB_ENV}
        echo "CI_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
        echo "CI_BRANCH=${{ github.ref_name }}" >> ${GITHUB_ENV}

    - name: Cache npm deps
      if: inputs.install-packages == 'true'
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: src/app/static/node_modules
        key: node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-${{ env.NODE_VERSION }}-

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Install CodeCov
      run: npm install codecov -g
      shell: bash

    - name: Install npm deps
      if: steps.npm-cache.outputs.cache-hit != 'true' && inputs.install-packages == 'true'
      run: npm ci --silent --prefix=src/app/static
      shell: bash

    - name: Compile kotlin
      run: src/gradlew -p src app:compileKotlin
      shell: bash
