name: Make Shared Environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache npm deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('src/app/static/package-lock.json') }}
          restore-keys: npm-

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install CodeCov
      run: npm install codecov -g
      shell: bash

    - name: Install npm deps
      run: npm ci --prefix=src/app/static
      shell: bash

    - name: Compile kotlin
      run: src/gradlew -p src app:compileKotlin
      shell: bash
