name: Make Shared Environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache npm deps
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install CodeCov
      run: npm install codecov -g
      shell: bash

    - name: Install npm deps
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci --silent --prefix=src/app/static
      shell: bash

    - name: Install npm deps from cache
      if: steps.npm-cache.outputs.cache-hit == 'true'
      run: npm ci --cache ${{ steps.npm-cache-dir.outputs.dir }} --prefer-offline --silent --no-audit --prefix=src/app/static
      shell: bash

    - name: Compile kotlin
      run: src/gradlew -p src app:compileKotlin
      shell: bash

    - name: Common env vars
      run: github-action-scripts/common
      shell: bash
