build:
  maxIssues: 15

comments:
   active: false

formatting:
  NoWildcardImports:
    active: false
  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: false
    excludes: ['**/HintrAPIClient.kt']

style:
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  WildcardImport:
    active: false
