on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Build and Push Image

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: mrc-ide/hint/.github/workflows/make-shared-env.yml@mrc-5246

            - name: Build
              run: github-action-scripts/build.sh

            - name: Push
              run: github-action-scripts/push.sh
