on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test CLI

env:
  TAG_DH: mrcide/hint-user-cli
  TAG_GHCR: mrc-ide/hint-user-cli

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared env
              uses: ./.github/actions/make-shared-env

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Login to GHCR (GitHub Packages)
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Run deps
              run: scripts/run-dependencies.sh

            - name: Test CLI
              run: src/gradlew -p src :userCLI:test -x app:compileFrontEnd -x app:copyAssets

            - name: Build docker image
              run: |
                rm -f /etc/hint/config.properties
                src/gradlew -p src :userCLI:docker -i -Pdocker_version=$CI_SHA -x app:compileFrontEnd -x app:copyAssets
              env:
                CI_SHA: ${{steps.ci-env.outputs.CI_SHA}}
            
            - name: Push image
              run: |
                docker tag "$TAG_DH_SHA" "$TAG_DH_BRANCH" "$TAG_GHCR_SHA" "$TAG_GHCR_BRANCH"
                docker push "$TAG_DH_SHA" "$TAG_DH_BRANCH" "$TAG_GHCR_SHA" "$TAG_GHCR_BRANCH"
              env:
                TAG_DH_SHA: ${{env.TAG_DH}}:${{steps.ci-env.outputs.CI_SHA}}
                TAG_DH_BRANCH: ${{env.TAG_DH}}:${{steps.ci-env.outputs.CI_BRANCH}}
                TAG_GHCR_SHA: ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_SHA}}
                TAG_GHCR_BRANCH: ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_BRANCH}}
