on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Lint Back End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared env
              uses: ./.github/actions/make-shared-env
              with:
                install-packages: 'false'

            - name: Lint back end
              run: src/gradlew -p src app:detektMain -x app:compileFrontEnd -x app:copyAssets
