on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Make Shared Environment

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Make base image
              run: github-action-scripts/make-base-image.sh