on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test ADR Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Run deps
              run: scripts/run-dependencies.sh

            - name: Start Kotlin server
              run: scripts/run-kotlin-server.sh

            - name: Test front end (ADR)
              run: npm run adr-integration-test --prefix=src/app/static
