on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/make-shared-env.yml

            - name: Test front end
              run: github-action-scripts/test-front-end.sh
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
