on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Back End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Run deps
              run: scripts/run-dependencies.sh

            - uses: satackey/action-docker-layer-caching@v0.0.11
              continue-on-error: true

            - name: Test back end
              run: |
                src/gradlew -p src :app:detektMain -PexcludeADR=true :app:test :app:jacocoTestReport
                codecov -p . -f src/app/coverage/test/*.xml
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
