on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make base image
              run: github-action-scripts/make-base-image.sh

            - name: Test front end
              run: github-action-scripts/test-front-end.sh
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3