on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test ADR Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Test front end
              run: github-action-scripts/test-adr-front-end.sh