on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test ADR Back End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Test back end
              run: github-action-scripts/test-adr-back-end.sh