on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

name: Back-end tests

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
               node-version: 14.x

            - name: Install Packages
              run: npm ci --prefix=src/app/static

            - name: Run Dependencies
              run: ./scripts/run-dependencies-half.sh
    wait-for-db:
          runs-on: ubuntu-latest
          container: hint_db
          steps:
              - name: Wait for DB
                run: ./wait-for-db
    test-backend:
          runs-on: ubuntu-latest
          steps:
            - name: Complete setup
              run: ./scripts/run-dependencies-other-half.sh

            - name: Test Back-end
              run: ./src/gradlew -p src :app:detektMain -PexcludeADR=true :app:test :userCLI:test :app:jacocoTestReport && codecov -p .. -f app/coverage/test/*.xml