on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Run deps for integration tests
              run: github-action-scripts/run-dependencies-for-integration-tests.sh

            - name: Lint
              run: npm run lint --prefix=src/app/static -- --quiet

            # - name: Setup tmate session
            #   uses: mxschmitt/action-tmate@v3
            # - name: Unit tests
            #   run: npm run test --prefix=src/app/static

            - name: Integration tests
              run: npm run integration-test --prefix=src/app/static

            - name: CodeCov
              run: |
                codecov -p . -f src/app/static/coverage/unit/*.json
                codecov -p . -f src/app/static/coverage/integration/*.json
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
