on:
    workflow_run:
        workflows: [Make shared image]
        types:
            - completed

name: Test Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run dependencies
              run: ./buildkite/test-front-end.sh 
