on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test ADR Back End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: mrc-ide/hint/.github/workflows/make-shared-env.yml@mrc-5246

            - name: Test back end
              run: github-action-scripts/test-adr-back-end.sh