on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test CLI

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Make shared image
              uses: ./.github/actions/make-shared-env

            - name: Run deps
              run: scripts/run-dependencies.sh

            - name: Test CLI
              run: src/gradlew -p src :userCLI:test -x app:compileFrontEnd -x app:copyAssets

            - name: Build docker image
              run: |
                rm -f /etc/hint/config.properties
                src/gradlew -p src :userCLI:docker -i -Pdocker_version=${CI_SHA:0:7} -x app:compileFrontEnd -x app:copyAssets
            
            - name: Push image
              run: |
                docker tag "${CI_ORG}/hint-user-cli:${CI_SHA:0:7}" "${CI_ORG}/hint-user-cli:${CI_BRANCH}"
                docker push "${CI_ORG}/hint-user-cli:${CI_SHA:0:7}"
                docker push "${CI_ORG}/hint-user-cli:${CI_BRANCH}"
