on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Browser E2E

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: mrc-ide/hint/.github/workflows/make-shared-env.yml@mrc-5246

            - name: Test browser e2e
              run: github-action-scripts/test-browser-e2e.sh
