on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Front End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: mrc-ide/hint/.github/workflows/make-shared-env.yml@mrc-5246

            - name: Test front end
              run: github-action-scripts/test-front-end.sh
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
