on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

name: Front-end tests

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
               node-version: 14.x

            - name: Install Packages
              run: npm ci

            - name: Front-end tests
              run: npm run test