on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

name: Test Back End

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Make shared env
              uses: ./.github/actions/make-shared-env
              with:
                install-packages: 'false'

            - name: Run deps
              run: scripts/run-dependencies.sh

            - name: Prep back end tests
              run: |
                mkdir -p src/app/static/public
                mkdir -p src/app/static/public/css
                yes ".class {height: 500px;}" | head -n 200 >> src/app/static/public/css/app.css

            - name: Test back end
              run: |
                src/gradlew -p src -PexcludeADR=true :app:test --parallel :app:jacocoTestReport -x app:compileFrontEnd
                codecov -p . -f src/app/coverage/test/*.xml
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
